### ISSUE TITLE
Would it possible run in Py 3.8 or 3.10?

### ISSUE THREAD

**Issue by yifanfu01** [kaifuchenlab/MEBOCOST#1]
Thank you authors.

**Comment by zhengrongbin** [comment]
Hi, yes, I think so. We suggest to use python3.12 and install dependencies in the requirement.txt to avoid version conflict problem and related errors. However, you can still try python3.10 and python8. I believe python3.10 works even with the same dependencies in the requirement.txt, but please remove the specified versions in the requirement.txt if you were trying python3.8, just let the pip to determine which version of the listed software in the requirement.txt based on your environment. If the pip cannot find suitable version for any dependencies, I would recommend trying at least python 3.10.
