### ISSUE TITLE
Running on multiple conditions

### ISSUE THREAD

**Issue by NeuralBind** [kaifuchenlab/MEBOCOST#2]
Hello, i have a short question. I am currently running it for multiple conditions. I run it by pooling all the cells together with different identifiers per condition.
In case i want to use the plot funtions, would it be statistically correct to just plot the based on the senders, receivers of focus param? Using plots like the eventum bar, seem to miss some of the cell groups.

Thank you in advance!!:)

**Comment by zhengrongbin** [comment]
Thanks for using mebocost. I am not sure if I got you correctly, and why it missed some of the cell groups. If you set the focused senders and receivers, the eventnum bar plot will only show you the number of communications identified associated with the focused senders and receivers, so will not show other cell groups that did not specified. Keep empty list if you do not specify cell groups of focus.

**Comment by NeuralBind** [comment]
Thanks a lot !! it was a small bug in my code that was thresholding some of the connections. 

Is it possible in the current version to run the pathway analysis like in v1.0.3 ( in the other github repo) or it's  an on-going process?

**Comment by zhengrongbin** [comment]
Thank you for the question. Since we are still developing the pathway analysis module, I removed that function from this version. We will release it once the module has matured.

**Comment by NeuralBind** [comment]
Makes sense, looking forward to it!

**Comment by zhengrongbin** [comment]
Glad to hear that. For metabolic balance results, please refer to FBA software, such as scFBA/COMPASS as you mentioned, or scFEA and other related.
