### ISSUE TITLE
How to add metabolites that are not included in MEBOCOST but are of interest to me?

### ISSUE THREAD

**Issue by xxz19900** [kaifuchenlab/MEBOCOST#4]
Hi, Rongbin. MEBOCOST is a very useful tool for researcher focusing on the immunometabolism. Is it possible to provide an interface to extend the metabolite library that can be analyzed?

**Comment by zhengrongbin** [comment]
> Hi, Rongbin. MEBOCOST is a very useful tool for researcher focusing on the immunometabolism. Is it possible to provide an interface to extend the metabolite library that can be analyzed?

Thank you for your interest in using mebocost. Yes, you can add metabolite-sensor pairs of your own interest, but we currently don't have a interface to link with the tool. To do that in local laptop, you can pass the require information to the tool by editing two files. First, data/mebocost_db/human/metabolite_associated_gene_reaction_HMDB_summary.tsv - add lines to indicate metabolite names, HMDB_ID, gene, and direction. Gene refers to enzymes. 
Second, data/mebocost_db/human/met_sen_October-25-2022_14-52-47.tsv - the key columns are HMDB_ID, standard_metName, and Gene_name. Gene_name refers to gene symbol of sensor proteins to the metabolite.
