### ISSUE TITLE
KeyError: 'ERROR: the config path is not exist!'

### ISSUE THREAD

**Issue by wuxiangning** [kaifuchenlab/MEBOCOST#6]
Hello, thank you very much for providing such a convenient tool for metabolite analysis. 
However, after I recently activated a new environment and used the package to create mebo_obj, I was unable to complete the "Aggregating metabolite enzyme expression" and subsequent analysis steps. The error message provided by my Jupyter is KeyError: 'ERROR: the config path is not exist!'. However, when I checked print(mebo_obj.config_path), it does show a config path.
What could be causing this error?
Thanks!
![image](https://github.com/user-attachments/assets/a3cddc9d-1cd2-4395-b411-d441b9aea352)
![image](https://github.com/user-attachments/assets/ec133629-0e68-4762-a65d-9256e1adce06)

**Comment by zhengrongbin** [comment]
Hi, can you find where is the mebocost.conf located, then provide a absolute path to mebo_obj.config_path?

**Comment by wuxiangning** [comment]
Hello, I'm not quite sure what you mean. I tried entering print(mebo_obj.config_path) and the result was ./mebocost.conf. I'm not sure if this result is correct. Could you provide a clearer solution?
Thank you!
![image](https://github.com/user-attachments/assets/d7ef39ef-60f4-4a1f-83c6-d0235d4bc830)

**Comment by zhengrongbin** [comment]
Can you show me your folder structure on your laptop for MEBOCOST? 
Mebocost use relative path for mebocost.conf in our example, so you may get error if you are not running the notebook in the same folder with mebocost.conf. In that case, you can provide the absolute  mebocost.conf path on your laptop to the create_obj, or directly pass to mebo_obj.config_path.

**Comment by wuxiangning** [comment]
Hello!
1、Do you mean to directly check the directory path of the MEBOCOST I have installed? I have looked at the folder structure, and the first image includes the output results. 
I am not sure how to provide the absolute mebocost.conf path to create_obj or directly pass it to mebo_obj.config_path. Could you please provide the code for this part?
2、Regarding the issue of not being able to display UMAP plots using scanpy with the demo file, my own h5ad file works perfectly with the exact same code for plotting. I also tried importing the demo file into a newly created environment where scanpy is freshly installed, but the demo file still fails to generate the UMAP plot. Furthermore, both the demo file and my own file cannot be used properly with the MEBOCOST package. I am not sure what is causing this issue; perhaps the demo file needs to be updated?
Thank you very much.
![image](https://github.com/user-attachments/assets/605e90d8-09d6-4547-bb34-589b3a9b2c27)

**Comment by zhengrongbin** [comment]
problem solved through email conversations, so close.
